name: Build rkp-ipid.ipk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc \
          wget unzip python3

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-*.tar.xz
        mv openwrt-sdk-*/ sdk/

    - name: Prepare package directory
      run: |
        mkdir -p sdk/package/rkp-ipid/src
        cp src/* sdk/package/rkp-ipid/src/
        cp Makefile sdk/package/rkp-ipid/

    - name: Build package
      run: |
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make package/rkp-ipid/compile V=s

    - name: Upload .ipk
      uses: actions/upload-artifact@v3
      with:
        name: rkp-ipid-ipk
        path: sdk/bin/packages/*/*/rkp-ipid*.ipk

