name: Build kmod-rkp-ipid for OpenWrt

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build in container
        uses: docker://openwrt/sdk:x86-generic
        with:
          args: |
            sh -c "
              ./scripts/feeds update -a &&
              ./scripts/feeds install -a &&
              mkdir -p package/rkp-ipid &&
              cp -r src/* package/rkp-ipid/ &&
              cp Makefile package/rkp-ipid/Makefile &&
              make defconfig &&
              echo 'CONFIG_PACKAGE_kmod-rkp-ipid=y' >> .config &&
              make package/rkp-ipid/compile V=s
            "


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kmod-rkp-ipid-ipk
          path: bin/packages/*/base/kmod-rkp-ipid_*.ipk

env:
  ACTIONS_RUNNER_DEBUG: false
  DEBIAN_FRONTEND: noninteractive


